### ISSUE TITLE
Allow different algorithms

### ISSUE THREAD

**Issue by JosuaKrause** [JosuaKrause/curl-chk#4]
Right now only md5 is supported. sha1 would be a start..

**Comment by remram44** [comment]
Algorithms with different digest sizes are probably easy to add :smile:

**Comment by JosuaKrause** [comment]
Not sure if I understand correctly. The digests would be distinguished by the key eg. `example.com/#sha1=...`, `example.com/#md5=...`. However, for the explicit digest the argument will likely be changed from `--md5 ...` to `--digest md5:...` or something. Not sure yet.
The biggest problem is finding a reliable cross-platform no-setup way to compute the digests.

**Comment by remram44** [comment]
You don't need md5: sha1: prefixes since you can distinguish them by length. SHA-1 has a 160 bits digest (40 hex digits) while MD5 has 128 bits (32 digits).

**Comment by JosuaKrause** [comment]
Yes, but sha1 vs. sha256? There needs to be some way to specify the algorithm.
